### ISSUE TITLE
How to invoke dom-distiller on a webpage?

### ISSUE THREAD

**Issue by sanathp** [chromium/dom-distiller-dist#2]
can is use dom-distiller js file to get the content from a webpage if i inject the js file ?
how to invoke the distill function ?

Thanks in advance

**Comment by wychen** [comment]
Following the steps in https://github.com/chromium/dom-distiller#developer-extension might be an easy first step.

**Comment by sanathp** [comment]
Thanks for the instructions. Its working now :)
